# Configuración de pre-commit para herramientas dentro de .code_quality
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Última versión estable
    hooks:
      - id: black
        args: ["--config", ".code_quality/pyproject.toml"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Última versión estable
    hooks:
      - id: flake8
        args: ["--config", ".code_quality/.flake8"]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args: ["--rcfile", ".code_quality/.pylintrc"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", ".code_quality/bandit", "-r", "app"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--config-file", ".code_quality/mypy"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
